### ISSUE TITLE
銘柄詳細、日本酒詳細に投稿一覧がない

### ISSUE THREAD

**Issue by nichesuch** [Code-for-SAKE/Sakepedia-Nuxt3#57]
酒蔵詳細にあるように、投稿一覧をつける。

**Comment by JQinglong** [comment]
下記タイミングで追加されていると思います。

https://github.com/Code-for-SAKE/Sakepedia-Nuxt3/commit/3b2e22ad3975951c5924fac7563a4f318cbe11e8#diff-d5d2482a774331f3ecdf89906f49bef16f36dfc334cd34f88cefb6b1d3638e81
