### ISSUE TITLE
日本酒追加・編集画面で、分類、合うおつまみをプルダウンで指定できるようにする

### ISSUE THREAD

**Issue by JQinglong** [Code-for-SAKE/Sakepedia-Nuxt3#70]

**Comment by JQinglong** [comment]
参考
https://brycecameron.com.au/blog/nuxt-ui-multi-select-dropdown

**Comment by nichesuch** [comment]
合うおつまみについて
TagSelect.vueというcomponentを作ってあるので、使ってください。

分類も同じでよいかも。

**Comment by nichesuch** [comment]
データとしてはstring[]で持つようにしてください
