### ISSUE TITLE
英語名の日本酒が日本語サイトだと日本語に変換される（スマホ）

### ISSUE THREAD

**Issue by youkey0211** [Code-for-SAKE/Sakepedia-Nuxt3#73]
No6→6位

**Comment by nichesuch** [comment]
Google翻訳で自動翻訳しているブラウザだと発生する。

言語設定をHeadで通知できるかも。

**Comment by nichesuch** [comment]
html lang="en"になっている。
言語設定に合わせる。

**Comment by nichesuch** [comment]
@AlixFachin こちらで対応できました！ #101

**Comment by nichesuch** [comment]
Googleの自動翻訳は
html lang="ja"に設定してもダメでした。
